export const metadata = {
  title: "Terms and Conditions | HandwritingTool",
  description:
    "Read the terms and conditions for using HandwritingTool, including service use, user responsibility, intellectual property, and liability.",
  alternates: {
    canonical: "/terms",
  },
  openGraph: {
    title: "Terms and Conditions | HandwritingTool",
    description:
      "Read the terms and conditions for using HandwritingTool, including service use, user responsibility, intellectual property, and liability.",
    url: "/terms",
    type: "website",
  },
  twitter: {
    card: "summary",
    title: "Terms and Conditions | HandwritingTool",
    description:
      "Read the terms and conditions for using HandwritingTool, including service use, user responsibility, intellectual property, and liability.",
  },
};

const sections = [
  {
    title: "Use of Service",
    text: "HandwritingTool is provided for general, educational, and personal use. You agree not to use this tool for any illegal, harmful, or unethical purposes.",
  },
  {
    title: "User Responsibility",
    text: "You are fully responsible for how you use the content generated by this tool. We do not take responsibility for misuse or inappropriate use of generated material.",
  },
  {
    title: "Academic Integrity and Acceptable Use",
    text: "HandwritingTool is intended for permitted digital formatting, study notes, drafts, worksheets, examples, and personal or educational productivity. You agree not to use the service to misrepresent work, bypass academic rules, deceive teachers or institutions, or violate any school, college, workplace, or legal policy.",
  },
  {
    title: "Intellectual Property",
    text: "All content, design elements, and functionality of this website are owned by HandwritingTool unless stated otherwise. You may not copy, reproduce, or redistribute any part of the website without permission.",
  },
  {
    title: "Service Availability",
    text: "We aim to keep the website available at all times. However, we do not guarantee uninterrupted access and may perform updates, maintenance, or improvements without prior notice.",
  },
  {
    title: "Limitation of Liability",
    text: "HandwritingTool is provided as is without warranties of any kind. We are not liable for any losses, damages, or issues resulting from the use of this website.",
  },
  {
    title: "Updates to Terms",
    text: "We may update these terms at any time. Continued use of the website means you accept the updated terms.",
  },
];

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-4xl px-4 py-16 sm:px-6 lg:px-8">
      <article className="rounded-[32px] border border-slate-200 bg-white p-8 shadow-card lg:p-12">
        <p className="text-sm font-semibold uppercase tracking-[0.24em] text-brand-blue">Terms and Conditions</p>
        <h1 className="mt-3 text-4xl font-semibold tracking-tight text-slate-950">Terms and Conditions</h1>
        <p className="mt-6 text-lg leading-8 text-slate-600">
          Welcome to HandwritingTool. By accessing and using this website, you agree to the following terms and
          conditions. Please read them carefully before using the service.
        </p>

        <div className="mt-10 space-y-8">
          {sections.map((section) => (
            <section key={section.title}>
              <h2 className="text-2xl font-semibold text-slate-950">{section.title}</h2>
              <p className="mt-4 text-lg leading-8 text-slate-600">{section.text}</p>
            </section>
          ))}
        </div>

        <p className="mt-10 rounded-2xl border border-blue-100 bg-blue-50 px-5 py-4 text-base font-semibold text-brand-blue">
          If you do not agree with these terms, please do not use the website.
        </p>
      </article>
    </main>
  );
}
