import type { Metadata } from "next";
import Link from "next/link";
import { ContributionForm } from "@/components/ContributionForm";
import { siteAuthor } from "@/lib/author";
import { defaultSocialImage } from "@/lib/seo";

const title="Education Write for Us & Guest Posts | HandwritingTool";
const description="Write for HandwritingTool and share useful content about handwriting, education, EdTech, note-taking and student productivity. View our guest post guidelines.";
const canonical="https://handwritingtool.com/write-for-us";
export const metadata:Metadata={title,description,alternates:{canonical},robots:{index:true,follow:true},openGraph:{title,description,url:canonical,type:"website",images:[defaultSocialImage]},twitter:{card:"summary_large_image",title,description,images:[defaultSocialImage.url]}};
const topics=["Handwriting improvement and calligraphy","Education and online learning","Study techniques and student productivity","Note-taking, journaling and organization","EdTech and educational software","Writing tools and applications","Fonts, typography and digital writing","Teacher and classroom resources","Responsible AI tools for education and writing"];
const guidelines=["Content must be original, useful and written for HandwritingTool’s audience.","Recommended length is at least 1,000 words, but quality is more important than word count.","Submissions must not be copied, spun, mass-produced or already published elsewhere.","Claims and statistics should include trustworthy sources.","Use short paragraphs, descriptive headings and practical examples.","Images must be original, licensed or properly attributed.","Promotional content and links are subject to editorial review.","HandwritingTool may edit content for clarity, formatting, accuracy and SEO.","Submission does not guarantee publication.","Content must remain relevant to handwriting, education, writing, learning, productivity or EdTech."];
const steps=["Send your proposed topic and a short outline.","Include your name, expertise, website and target URL, if applicable.","Our team reviews the topic for relevance and quality.","If accepted, we provide the next steps and any applicable sponsorship information.","The final article is reviewed before publication."];
const faqs=[
 {q:"Does HandwritingTool accept education guest posts?",a:"Yes. We welcome original education guest post ideas that offer practical value and fit our focus on handwriting, learning, writing, productivity or EdTech."},
 {q:"What topics can contributors submit?",a:"Contributors can propose content about handwriting, calligraphy, online learning, study techniques, student productivity, note-taking, journaling, educational software, writing tools, typography, classroom resources and responsible AI for education."},
 {q:"Are sponsored posts available?",a:"We accept a limited number of relevant sponsored articles and brand collaborations. Contact us with your proposed topic, website URL and requirements to receive our current rates."},
 {q:"Is publication guaranteed?",a:"No. Every submission is reviewed for relevance, originality, usefulness and editorial quality, and submission does not guarantee publication."},
 {q:"Can contributors include a relevant link?",a:"You may propose a relevant link, but all promotional links and placements are subject to editorial review and applicable search-engine guidelines. Sponsored outbound links will use appropriate sponsored attributes."},
 {q:"How long does the review process take?",a:"We review submissions as soon as possible. Timing varies with submission volume and the amount of editorial review required."}
];
export default function Page(){
 const email=process.env.NEXT_PUBLIC_CONTACT_EMAIL??siteAuthor.email;
 const schema=[{"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:"https://handwritingtool.com/"},{"@type":"ListItem",position:2,name:"Write for Us",item:canonical}]},{"@context":"https://schema.org","@type":"FAQPage",mainEntity:faqs.map(({q,a})=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))}];
 return <main><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
 <section className="hero-surface border-b border-slate-200"><div className="mx-auto max-w-5xl px-4 py-20 text-center sm:px-6 sm:py-24"><p className="text-sm font-semibold uppercase tracking-[.24em] text-brand-blue">Contribute to HandwritingTool</p><h1 className="mx-auto mt-4 max-w-4xl text-4xl font-semibold tracking-tight text-slate-950 sm:text-5xl lg:text-6xl">Write for Us: Handwriting, Education and Productivity</h1><p className="mx-auto mt-6 max-w-3xl text-lg leading-8 text-slate-600">HandwritingTool welcomes useful, original and practical contributions from educators, writers, students, productivity experts, EdTech professionals and relevant brands. If you are looking for an education write for us opportunity, share an idea that helps readers learn, write or organize their work.</p><a href="#submit-your-idea" className="mt-8 inline-flex min-h-12 items-center rounded-full bg-brand-blue px-7 py-3 font-semibold text-white shadow-lg shadow-blue-200 hover:bg-blue-700">Submit Your Idea</a></div></section>
 <div className="mx-auto max-w-6xl space-y-20 px-4 py-16 sm:px-6 lg:px-8">
 <section><h2 className="text-3xl font-semibold text-slate-950 sm:text-4xl">Topics We Accept</h2><p className="mt-4 max-w-3xl text-lg leading-8 text-slate-600">Contribute to an education blog with focused, experience-led advice. Suitable pitches include handwriting write for us, EdTech write for us, writing tools write for us, note-taking write for us and student productivity write for us themes.</p><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{topics.map((x,i)=><article key={x} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-card"><span className="text-sm font-bold text-brand-blue">0{i+1}</span><h3 className="mt-3 text-lg font-semibold text-slate-900">{x}</h3></article>)}</div><p className="mt-6 rounded-3xl border border-amber-200 bg-amber-50 p-6 leading-7 text-amber-950"><strong>Topics we do not accept:</strong> casino, gambling, adult content, payday loans, CBD, cryptocurrency promotions or other irrelevant subjects.</p></section>
 <section className="grid gap-8 lg:grid-cols-[.8fr,1.2fr]"><div><h2 className="text-3xl font-semibold text-slate-950 sm:text-4xl">Education Guest Post Guidelines</h2><p className="mt-4 text-lg leading-8 text-slate-600">Review these requirements before you submit a guest post education proposal.</p></div><ul className="rounded-[32px] border border-slate-200 bg-white p-8 shadow-card">{guidelines.map(x=><li key={x} className="flex gap-3 border-b border-slate-100 py-3 last:border-0"><span className="text-brand-green">✓</span><span className="leading-7 text-slate-700">{x}</span></li>)}</ul></section>
 <section><h2 className="text-3xl font-semibold text-slate-950 sm:text-4xl">Editorial Contributions and Sponsored Partnerships</h2><div className="mt-8 grid gap-6 lg:grid-cols-2"><article className="rounded-[32px] border border-blue-100 bg-blue-50 p-8"><h3 className="text-2xl font-semibold">Editorial Contributions</h3><p className="mt-4 leading-7 text-slate-700">For educators, writers and subject experts who want to share genuinely useful knowledge with the audience.</p></article><article className="rounded-[32px] border border-emerald-100 bg-emerald-50 p-8"><h3 className="text-2xl font-semibold">Sponsored Content and Brand Partnerships</h3><p className="mt-4 leading-7 text-slate-700">For relevant EdTech companies, education brands, writing-tool businesses and agencies interested in sponsored articles or suitable collaborations.</p><p className="mt-4 font-medium leading-7">We accept a limited number of relevant sponsored articles and brand collaborations. Contact us with your proposed topic, website URL and requirements to receive our current rates.</p></article></div><p className="mt-6 rounded-2xl border border-slate-200 bg-white p-5 leading-7 text-slate-600">All links and sponsored placements are reviewed and handled according to the website’s editorial standards and applicable search-engine guidelines. Future paid or sponsored outbound links will support <code>rel=&quot;sponsored&quot;</code>. We do not promise rankings or SEO results.</p></section>
 <section className="grid gap-8 lg:grid-cols-[.8fr,1.2fr]"><div><h2 className="text-3xl font-semibold text-slate-950 sm:text-4xl">How to Submit</h2><p className="mt-4 text-lg text-slate-600">A clear pitch helps us assess your idea.</p></div><ol className="space-y-4">{steps.map((x,i)=><li key={x} className="flex gap-4 rounded-2xl border border-slate-200 bg-white p-5"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-brand-blue font-semibold text-white">{i+1}</span><p className="pt-1 leading-7 text-slate-700">{x}</p></li>)}</ol></section>
 <section id="submit-your-idea" className="scroll-mt-24 rounded-[36px] border border-slate-200 bg-white p-6 shadow-card sm:p-10"><h2 className="text-3xl font-semibold text-slate-950 sm:text-4xl">Submit Your Idea</h2><p className="mt-4 text-lg leading-8 text-slate-600">Use our existing contact service or email <a className="font-semibold text-brand-blue" href={`mailto:${email}`}>{email}</a> directly.</p><ContributionForm action={`https://formsubmit.co/ajax/${email}`} supportEmail={email}/></section>
 <section><h2 className="text-3xl font-semibold text-slate-950 sm:text-4xl">Frequently Asked Questions</h2><div className="mt-8 grid gap-4">{faqs.map(({q,a})=><details key={q} className="group rounded-2xl border border-slate-200 bg-white p-6"><summary className="cursor-pointer list-none text-lg font-semibold">{q}<span className="float-right text-brand-blue group-open:rotate-45">+</span></summary><p className="mt-4 leading-7 text-slate-600">{a}</p></details>)}</div><p className="mt-8 text-center text-slate-600">More questions? <Link href="/contact" className="font-semibold text-brand-blue">Contact HandwritingTool</Link>.</p></section>
 </div></main>;
}
